[package]
name = "quick-xml"
version = "0.6.1"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "High performance xml reader and writer"

documentation = "https://docs.rs/quick-xml"
repository = "https://github.com/tafia/quick-xml"

readme = "README.md"
keywords = ["xml", "reader", "parser", "writer", "html"]
categories = ["encoding", "parsing", "text-processing"]
license = "MIT"
license-file = "LICENSE-MIT.md"

[badges]
travis-ci = { repository = "tafia/quick-xml" }

[dependencies]
from-ascii = "0.0.1"
encoding_rs = "0.5.0"
error-chain = "0.10.0"

[dev-dependencies]
xml-rs = "0.4.1"

[lib]
bench = false
