[package]
name = "quick-xml"
version = "0.9.3"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "High performance xml reader and writer"

documentation = "https://docs.rs/quick-xml"
repository = "https://github.com/tafia/quick-xml"

readme = "README.md"
keywords = ["xml", "reader", "parser", "writer", "html"]
categories = ["encoding", "parsing", "text-processing"]
license = "MIT"

[badges]
travis-ci = { repository = "tafia/quick-xml" }

[dependencies]
encoding_rs = "0.7.0"
error-chain = "0.10.0"
memchr = "1.0.1"

[dev-dependencies]
xml-rs = "0.6.1"

[lib]
bench = false
