[package]
name = "fast-xml"
version = "0.23.0-alpha3"
description = "High performance xml reader and writer"
edition = "2018"

documentation = "https://docs.rs/fast-xml"
repository = "https://github.com/Mingun/fast-xml"

keywords = ["xml", "serde", "parser", "writer", "html"]
categories = ["encoding", "parsing", "parser-implementations"]
license = "MIT"

[dependencies]
encoding_rs = { version = "0.8.26", optional = true }
serde = { version = "1.0", optional = true }
memchr = "2.3.4"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-value = "0.7"
regex = "1"

[lib]
bench = false

[features]
default = []
encoding = ["encoding_rs"]
serialize = ["serde"]
escape-html = []

[package.metadata.docs.rs]
features = ["serialize"]
